global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using FluentAssertions;
global using NUnit.Framework;
global using System.IO;
global using AdventOfCode2021.Tests.Helpers;